'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.269
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XS156LinearTesterPole.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("add_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property add_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property applications_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property applications_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_back_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_back_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_back_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_back_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_back_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_back_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_back_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_back_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_down_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_forward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_forward_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_forward_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_forward_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_forward_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_up_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_up_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_up_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_up_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BarCode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarCode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property computer_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property computer_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("computer_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_play_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_play_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_stop_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_stop_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copy_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property copy_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cut_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("cut_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property cut_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cut_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property delete_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disc_media_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disc_media_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disc_media_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disc_media_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disc_media_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("disc_media_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property disc_media_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disc_media_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property documents_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property documents_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("documents_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EjectNormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EjectNormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_closed_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_closed_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_closed_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property folder_closed_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property folder_open_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_open_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("home_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property home_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property mail_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property paste_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play1Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play1Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("print_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property print_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redo_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property redo_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("save_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property save_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stop1PressedBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop1PressedBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Telemecanique_Sensors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Telemecanique_Sensors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trash_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trash_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property trash_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property trash_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undo_32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property undo_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undo_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property YEILD_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("YEILD_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
